source: source
destination: site
markdown: rdiscount
pygments: true
pygments-cache: .pygments_cache
permalink: /blog/:year/:month/:day/:title
url: http://michaelahale.com
multiviews: true
sass: false
haml: true
post_defaults:
  layout: default